[build]
publish = "prod/wwwroot"

command = "dotnet workload install wasm-tools ; dotnet publish \"ROKAcademy/WebApp/WebApp.csproj\" -c Release -o prod"

[context.deploy-preview]
publish = "dev/wwwroot"
command = "dotnet workload install wasm-tools ; dotnet build \"ROKAcademy/WebApp/WebApp.csproj\" --configuration Release ; dotnet publish \"ROKAcademy/WebApp/WebApp.csproj\" -c Release --no-build -o dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/#*"
  to = "/index.html"
  status = 200
